name: CI
on:
  pull_request:
  schedule:
    - cron: "0 6 * * *"

jobs:
  mmo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - "2.7"
          - "3.6"
          - "3.8"
        mongodb_version:
          - "4.2"
          - "4.4"
        ansible_version:
          - stable-2.10
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install ansible-base (${{ matrix.ansible_version }})
      run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible_version }}.tar.gz --disable-pip-version-check

    - name: Install community.general
      run: ansible-galaxy collection install community.general

    - name: Install community.crypto
      run: ansible-galaxy collection install community.crypto

    - name: Install community.mongodb
      run: ansible-galaxy collection install community.mongodb

    - name: Create playbook to install repo for ${{ matrix.ansible_version }}
      run: |
         cat << EOF > /tmp/mongodb.yml
            - hosts: servers
              roles:
                - { role: mongodb_repository, mongodb_version: "${{ matrix.mongodb_version }}" }
         EOF

    - name: Execute playbook
      run: ansible-playbook -c local --become /tmp/mongodb.yml

    - name: Install the mongodb package
      run: apt install mongodb-org

    - name: Setup a MongoB Sharded Cluster
      run: |
        source bash/mmop_mongodb_cluster.sh;
        mmo_setup_cluster;
