name: CI
on:
  pull_request:
  schedule:
    - cron: "0 6 * * *"

jobs:
  mmo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - "3.6"
          - "3.8"
        mongodb_version:
          - "4.0"
          - "4.2"
          - "4.4"
        ansible_version:
          - stable-2.10
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install ansible-base (${{ matrix.ansible_version }})
      run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible_version }}.tar.gz --disable-pip-version-check

    - name: Install community.general
      run: ansible-galaxy collection install community.general

    - name: Install community.crypto
      run: ansible-galaxy collection install community.crypto

    - name: Install community.mongodb
      run: ansible-galaxy collection install community.mongodb

    - name: Create playbook to install repo for MongoDB ${{ matrix.ansible_version }}
      run: |
         cat << EOF > /tmp/mongodb.yml
            - hosts: servers
              roles:
                - { role: community.mongodb.mongodb_repository, mongodb_version: "${{ matrix.mongodb_version }}" }
         EOF

    - name: Execute playbook
      run: ansible-playbook -c local --become /tmp/mongodb.yml

    - name: Install the mongodb package
      run: sudo apt install mongodb-org

    # Deprecated
    #- name: Setup a MongoB Sharded Cluster
    #  run: |
    #    source bash/mmo_mongodb_cluster.sh;
    #    mmo_setup_cluster;

    - name: Install mtools
      run: pip install --user mtools[all]

    - name: Add mtools location to path
      run: echo "/home/runner/.local/bin" >> $GITHUB_PATH

    - name: Setup a MongoDB Sharded Cluster
      run: mlaunch --replicaset --sharded shard01 shard02 shard03 --auth --username admin --password admin

    #- name: Debug
    #  run: cat data/.mlaunch_startup
    - name: Pause to all a little time for replicaset to stablise
      run: sleep 10

    - name: Build and install the mm app
      run: python setup.py bdist_wheel && python -m pip install dist/mongodbmanager-*-py3-none-any.whl
      working-directory: python

    - name: Run mm command and get output from repl cmd
      id: mm
      run: |
        output=$(mm -D admin -u user -p password --repl)
        echo "$output"
        output="${output//'%'/'%25'}"
        output="${output//$'\n'/'%0A'}"
        output="${output//$'\r'/'%0D'}"
        echo "::set-output name=mm::$output"

    - name: Validate output of the repl command shard01
      uses: nick-invision/assert-action@v1
      with:
        expected: shard01
        actual: ${{ steps.mm.outputs.mm }}
        comparison: Contains

    - name: Validate output of the repl command shard02
      uses: nick-invision/assert-action@v1
      with:
        expected: shard02
        actual: ${{ steps.mm.outputs.mm }}
        comparison: Contains

    - name: Validate output of the repl command shard03
      uses: nick-invision/assert-action@v1
      with:
        expected: shard03
        actual: ${{ steps.mm.outputs.mm }}
        comparison: Contains

    - name: Validate output of the repl command shard001
      uses: nick-invision/assert-action@v1
      with:
        expected: configRepl
        actual: ${{ steps.mm.outputs.mm }}
        comparison: Contains

    - name: Validate output of the repl command PRIMARY
      uses: nick-invision/assert-action@v1
      with:
        expected: PRIMARY
        actual: ${{ steps.mm.outputs.mm }}
        comparison: Contains

    - name: Validate output of the repl command SECONDARY
      uses: nick-invision/assert-action@v1
      with:
        expected: SECONDARY
        actual: ${{ steps.mm.outputs.mm }}
        comparison: Contains

    - name: Run mm command and get output from summary cmd
      id: mm2
      run: |
        output=$(mm -D admin -u user -p password --summary)
        echo "$output"
        output="${output//'%'/'%25'}"
        output="${output//$'\n'/'%0A'}"
        output="${output//$'\r'/'%0D'}"
        echo "::set-output name=mm::$output"

    - name: Validate output of the summary command 1
      uses: nick-invision/assert-action@v1
      with:
        expected: "MongoDB Config Servers"
        actual: ${{ steps.mm2.outputs.mm }}
        comparison: Contains

    - name: Validate output of the summary command 2
      uses: nick-invision/assert-action@v1
      with:
        expected: "MongoDB mongos servers"
        actual: ${{ steps.mm2.outputs.mm }}
        comparison: Contains

    - name: Validate output of the summary command 3
      uses: nick-invision/assert-action@v1
      with:
        expected: "MongoDB mongod shard servers"
        actual: ${{ steps.mm2.outputs.mm }}
        comparison: Contains

    - name: Validate output of the summary command 3
      uses: nick-invision/assert-action@v1
      with:
        expected: "MongoDB shards"
        actual: ${{ steps.mm2.outputs.mm }}
        comparison: Contains

    - name: Validate output of the summary command 4
      uses: nick-invision/assert-action@v1
      with:
        expected: "shard01"
        actual: ${{ steps.mm2.outputs.mm }}
        comparison: Contains

    - name: Validate output of the summary command 5
      uses: nick-invision/assert-action@v1
      with:
        expected: "shard02"
        actual: ${{ steps.mm2.outputs.mm }}
        comparison: Contains

    - name: Validate output of the summary command 5
      uses: nick-invision/assert-action@v1
      with:
        expected: "shard03"
        actual: ${{ steps.mm2.outputs.mm }}
        comparison: Contains

    - name: Run mm command and get output from server_status instance cmd
      id: mm3
      run: |
        output=$(mm -D admin -u user -p password --server_status instance)
        echo "$output"
        output="${output//'%'/'%25'}"
        output="${output//$'\n'/'%0A'}"
        output="${output//$'\r'/'%0D'}"
        echo "::set-output name=mm::$output"

    - name: Validate output of the server_status command 1
      uses: nick-invision/assert-action@v1
      with:
        expected: "mongod"
        actual: ${{ steps.mm3.outputs.mm }}
        comparison: Contains

    - name: Validate output of the server_status command 2
      uses: nick-invision/assert-action@v1
      with:
        expected: "pid"
        actual: ${{ steps.mm3.outputs.mm }}
        comparison: Contains

    - name: Validate output of the server_status command 3
      uses: nick-invision/assert-action@v1
      with:
        expected: "uptime"
        actual: ${{ steps.mm3.outputs.mm }}
        comparison: Contains

    - name: Run mm command and get output from host_info os cmd
      id: mm4
      run: |
        output=$(mm -D admin -u user -p password --host_info os)
        echo "$output"
        output="${output//'%'/'%25'}"
        output="${output//$'\n'/'%0A'}"
        output="${output//$'\r'/'%0D'}"
        echo "::set-output name=mm::$output"

    - name: Validate output of the host_info command 1
      uses: nick-invision/assert-action@v1
      with:
        expected: "Linux Ubuntu"
        actual: ${{ steps.mm4.outputs.mm }}
        comparison: Contains

    - name: Validate output of the host_info command 2
      uses: nick-invision/assert-action@v1
      with:
        expected: "shard03"
        actual: ${{ steps.mm4.outputs.mm }}
        comparison: Contains

    - name: Run mm command with step_down
      id: mm5
      run: |
        mm -D admin -u user -p password --step_down shard01

    - name: Run mm command and get output from repl cmd with repeat
      id: mm6
      run: |
        mm -D admin -u user -p password --repl --repeat 5 > output2.log 2>&1
        output=$(cat output2.log)
        echo "$output"
        output="${output//'%'/'%25'}"
        output="${output//$'\n'/'%0A'}"
        output="${output//$'\r'/'%0D'}"
        echo "::set-output name=mm::$output"

    - name: Validate output of the repl cmd with repeat 1
      uses: nick-invision/assert-action@v1
      with:
        expected: "There has been 1 change in the cluster state since the last check"
        actual: ${{ steps.mm6.outputs.mm }}
        comparison: Contains

    - name: Validate output of the repl cmd with repeat 2
      uses: nick-invision/assert-action@v1
      with:
        expected: "There have been no state changes in the cluster since the last check"
        actual: ${{ steps.mm6.outputs.mm }}
        comparison: Contains
